### ISSUE TITLE
Publish on Docker Hub Registry

### ISSUE THREAD

**Issue by pandeiro** [artsince/docker-neo4j-auth#1]
This is a very useful addition to the `tpires/neo4j` image, especially now that Neo4J 2.2 **requires** setting authentication credentials in order to use the database at all.

Would you consider publishing this (and adding `docker pull` coordinates to the README)?

**Comment by ahmetkizilay** [comment]
hi @pandeiro,
That's a good idea, I guess I thought people would only discover this image on docker hub.

In the meantime, here's the registry address for this repo:
https://registry.hub.docker.com/u/ahmetkizilay/docker-neo4j-auth/
`docker pull ahmetkizilay/docker-neo4j-auth`

I also suggest you check out my other docker neo4j repository https://github.com/artsince/docker-neo4j. 
That one is a direct fork of `tpires/neo4j` image and that's the one I personally use.
https://registry.hub.docker.com/u/ahmetkizilay/docker-neo4j/
`docker pull ahmetkizilay/docker-neo4j`

**Comment by pandeiro** [comment]
Thanks @artsince, honestly I searched the registry and didn't find this (there are a lot of Neo4J images) and so I concluded it hadn't been published yet. My bad.

What is the difference between this and the docker-neo4j image?

**Comment by ahmetkizilay** [comment]
`docker-neo4j-auth` uses `tpires/neo4j` as the base image whereas `docker-neo4j` is a fork of the `tpires/neo4j` image. The functionality is pretty much the same, however I find `docker-neo4j` to be more elegant and less hacky.

**Comment by pandeiro** [comment]
Much obliged, Ahmet!
